services:
  - type: web
    name: catalogo-inmobiliario-pro
    env: python
    plan: starter # Plan de pago para que permita agregar discos fijos
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: mi_clave_secreta_123
    disk:
      name: datos-inmuebles
      mountPath: /var/data
      sizeGB: 1 # Espacio de sobra para miles de fotos de apartamentos ($0.25 USD/mes)